"""
One-off script: backfill `ticker` and `form_type` fields into the existing
data/fund-holdings.json, using the TICKER_MAP from fetch_13f.py.

This avoids re-running the full SEC EDGAR fetch (which requires the `edgar`
library that has compatibility issues with Python 3.13).

Usage:
    python3 scripts/backfill_tickers.py
"""
import json
import os
import re

# Copied from fetch_13f.py to keep this script self-contained.
TICKER_MAP = {
    "Apple Inc": "AAPL",
    "American Express Co": "AXP",
    "Bank America Corp": "BAC",
    "Bank of America Corp": "BAC",
    "Coca Cola Co": "KO",
    "Coca-Cola Co": "KO",
    "Chevron Corporation": "CVX",
    "Chevron Corp": "CVX",
    "Occidental Pete Corp": "OXY",
    "Occidental Petroleum Corp": "OXY",
    "Alphabet Inc": "GOOGL",
    "Chubb Ltd Switz": "CB",
    "Chubb Ltd": "CB",
    "Moodys Corp": "MCO",
    "Moody's Corp": "MCO",
    "Amazon Com Inc": "AMZN",
    "Amazon.com Inc": "AMZN",
    "Kraft Heinz Co": "KHC",
    "DaVita Inc": "DVA",
    "Citigroup Inc": "C",
    "General Motors Co": "GM",
    "General Motors": "GM",
    "Jefferies Financial Group": "JEF",
    "Liberty Formula One": "FWONA",
    "Liberty SiriusXM Group": "LSXMA",
    "Liberty Media Corp": "LSXMA",
    "Liberty Live Group": "LLYVA",
    "Verisign Inc": "VRSN",
    "VeriSign Inc": "VRSN",
    "Capital One Financial": "COF",
    "Nu Holdings Ltd": "NU",
    "Nu Holdings": "NU",
    "Floor & Decor Holdings": "FND",
    "T-Mobile US Inc": "TMUS",
    "Charter Communications": "CHTR",
    "Citizens Financial Group": "CFG",
    "Ally Financial Inc": "ALLY",
    "PNC Financial Services": "PNC",
    "Bank of New York Mellon": "BK",
    "US Bancorp": "USB",
    "Wells Fargo & Co": "WFC",
    "Wells Fargo & Company": "WFC",
    "JPMorgan Chase & Co": "JPM",
    "Goldman Sachs Group": "GS",
    "Morgan Stanley": "MS",
    "BlackRock Inc": "BLK",
    "Microsoft Corp": "MSFT",
    "Microsoft Corporation": "MSFT",
    "Nvidia Corp": "NVDA",
    "NVIDIA Corp": "NVDA",
    "NVIDIA Corporation": "NVDA",
    "Meta Platforms Inc": "META",
    "Meta Platforms": "META",
    "Facebook Inc": "META",
    "Tesla Inc": "TSLA",
    "Tesla, Inc.": "TSLA",
    "Berkshire Hathaway": "BRK.B",
    "Visa Inc": "V",
    "Mastercard Inc": "MA",
    "Johnson & Johnson": "JNJ",
    "Procter & Gamble": "PG",
    "UnitedHealth Group": "UNH",
    "Exxon Mobil Corp": "XOM",
    "Exxon Mobil": "XOM",
    "Pfizer Inc": "PFE",
    "AbbVie Inc": "ABBV",
    "Eli Lilly & Co": "LLY",
    "Eli Lilly and Co": "LLY",
    "Merck & Co": "MRK",
    "Merck & Co. Inc.": "MRK",
    "Caterpillar Inc": "CAT",
    "Home Depot": "HD",
    "The Home Depot": "HD",
    "Disney (Walt) Co": "DIS",
    "Walt Disney Co": "DIS",
    "Walt Disney Company": "DIS",
    "Netflix Inc": "NFLX",
    "Adobe Inc": "ADBE",
    "Salesforce Inc": "CRM",
    "Salesforce.com Inc": "CRM",
    "Oracle Corp": "ORCL",
    "Intel Corp": "INTC",
    "Cisco Systems": "CSCO",
    "Qualcomm Inc": "QCOM",
    "Broadcom Inc": "AVGO",
    "Advanced Micro Devices": "AMD",
    "AMD Inc": "AMD",
    "TSMC": "TSM",
    "Taiwan Semiconductor": "TSM",
    "Shopify Inc": "SHOP",
    "Square Inc": "SQ",
    "Block Inc": "SQ",
    "Coinbase Global": "COIN",
    "Robinhood Markets": "HOOD",
    "Palantir Technologies": "PLTR",
    "UiPath Inc": "PATH",
    "Twilio Inc": "TWLO",
    "Teladoc Health": "TDOC",
    "Zoom Video Communications": "ZM",
    "Spotify Technology": "SPOT",
    "Roblox Corp": "RBLX",
    "DraftKings Inc": "DKNG",
    "SoFi Technologies": "SOFI",
    "Rivian Automotive": "RIVN",
    "Lucid Group": "LCID",
    "Snowflake Inc": "SNOW",
    "Datadog Inc": "DDOG",
    "MongoDB Inc": "MDB",
    "Unity Software": "U",
    "Tesla": "TSLA",
    "Intuitive Surgical": "ISRG",
    "Stryker Corp": "SYK",
    "Medtronic plc": "MDT",
    "Boston Scientific": "BSX",
    "Edwards Lifesciences": "EW",
    "IDEXX Laboratories": "IDXX",
    "Vertex Pharmaceuticals": "VRTX",
    "Regeneron Pharmaceuticals": "REGN",
    "Moderna Inc": "MRNA",
    "BioNTech SE": "BNTX",
    "Gilead Sciences": "GILD",
    "Amgen Inc": "AMGN",
    "Bristol Myers Squibb": "BMY",
    "Schlumberger NV": "SLB",
    "Halliburton Co": "HAL",
    "ConocoPhillips": "COP",
    "EOG Resources": "EOG",
    "Pioneer Natural Resources": "PXD",
    "Devon Energy": "DVN",
    "Marathon Petroleum": "MPC",
    "Valero Energy": "VLO",
    "NextEra Energy": "NEE",
    "Duke Energy": "DUK",
    "Southern Company": "SO",
    "Lockheed Martin": "LMT",
    "Raytheon Technologies": "RTX",
    "RTX Corp": "RTX",
    "Northrop Grumman": "NOC",
    "Boeing Co": "BA",
    "The Boeing Company": "BA",
    "Airbus SE": "EADSY",
    "Ford Motor Co": "F",
    "Stellantis NV": "STLA",
    "Toyota Motor": "TM",
    "Costco Wholesale": "COST",
    "Walmart Inc": "WMT",
    "Target Corp": "TGT",
    "Lowe's Companies": "LOW",
    "Nike Inc": "NKE",
    "Starbucks Corp": "SBUX",
    "McDonald's Corp": "MCD",
    "Chipotle Mexican Grill": "CMG",
    "Coca-Cola Consolidated": "COKE",
    "PepsiCo Inc": "PEP",
    "Mondelez International": "MDLZ",
    "Kellogg Co": "K",
    "Conagra Brands": "CAG",
    "Tyson Foods": "TSN",
    "Archer-Daniels-Midland": "ADM",
    "FedEx Corp": "FDX",
    "United Parcel Service": "UPS",
    "Union Pacific": "UNP",
    "CSX Corp": "CSX",
    "Delta Air Lines": "DAL",
    "United Airlines": "UAL",
    "American Airlines": "AAL",
    "Southwest Airlines": "LUV",
    "Marriott International": "MAR",
    "Hilton Worldwide": "HLT",
    "Airbnb Inc": "ABNB",
    "Booking Holdings": "BKNG",
    "Expedia Group": "EXPE",
    "McDonald's": "MCD",
    "Goldman Sachs": "GS",
    "Berkshire Hathaway Inc": "BRK.B",
    "Situational Awareness Capital": "SAC",
    # ETFs and index funds (commonly held by Soros / Bridgewater)
    "State Str Spdr S&P 500 Etf T": "SPY",
    "Spdr S&P 500 Etf Trust": "SPY",
    "Select Sector Spdr Tr": "XLK",
    "Select Sector Spdr Trust": "XLK",
    "Spdr Series Trust": "SPY",
    "Ishares Tr": "IWM",
    "Ishares Trust": "IWM",
    "Ishares Core S&P 500 Etf": "IVV",
    "Ishares Msci Eafe Etf": "EFA",
    "Ishares Msci Emerg Markets Etf": "EEM",
    "Ishares 7-10 Year Treasury Bond": "IEF",
    "Ishares 20+ Year Treasury Bond": "TLT",
    "Ishares Russell 2000 Etf": "IWM",
    "Ishares S&P 500 Growth Etf": "IVW",
    "Ishares S&P 500 Value Etf": "IVE",
    "Ishares Global Clean Energy Etf": "ICLN",
    "Vanguard Index Fds": "VTI",
    "Vanguard Total Stock Market Etf": "VTI",
    "Vanguard S&P 500 Etf": "VOO",
    "Vanguard Ftse Emerg Markets": "VWO",
    "Vanguard Russell 2000 Etf": "VTWO",
    "Invesco Qqq Trust": "QQQ",
    "Invesco Qqq Trust Series 1": "QQQ",
    # Additional individual stocks (Soros / Bridgewater / ARK holdings)
    "Crispr Therapeutics Ag": "CRSP",
    "Crispr Therapeutics": "CRSP",
    "Tempus Ai Inc": "TEM",
    "Tempus Ai": "TEM",
    "Circle Internet Group Inc": "CRCL",
    "Circle Internet Group": "CRCL",
    "Coreweave Inc": "CRWV",
    "Coreweave": "CRWV",
    "Global Pmts Inc": "GPN",
    "Global Payments Inc": "GPN",
    "Electronic Arts Inc": "EA",
    "Electronic Arts": "EA",
    "Nvidia Corporation": "NVDA",
    "Bill Holdings Inc": "BILL",
    "Bill.Com Holdings Inc": "BILL",
    "Pg&E Corp": "PCG",
    "PG&E Corp": "PCG",
    "Pg&E": "PCG",
    "Micron Technology Inc": "MU",
    "Micron Technology": "MU",
    "Ge Vernova Inc": "GEV",
    "GE Vernova": "GEV",
    "Taiwan Semiconductor Manufac": "TSM",
    "Taiwan Semiconductor Manufacturing": "TSM",
    "Taiwan Semiconductor Adr": "TSM",
    "Novo Nordisk": "NVO",
    "Novo Nordisk A/S": "NVO",
    "AstraZeneca Plc": "AZN",
    "Astrazeneca": "AZN",
    "Shell Plc": "SHEL",
    "Shell": "SHEL",
    "Totalenergies Se": "TTE",
    "TotalEnergies": "TTE",
    "Bp Plc": "BP",
    "BP Plc": "BP",
    "Rio Tinto Plc": "RIO",
    "Rio Tinto": "RIO",
    "Bhp Group Ltd": "BHP",
    "BHP Group": "BHP",
    "Alibaba Group Holding": "BABA",
    "Alibaba Group": "BABA",
    "Tencent Holdings": "TCEHY",
    "Jd.Com Inc": "JD",
    "JD.com": "JD",
    "Pinduoduo Inc": "PDD",
    "PDD Holdings": "PDD",
    "Nio Inc": "NIO",
    "NIO Inc": "NIO",
    "Li Auto Inc": "LI",
    "Xpeng Inc": "XPEV",
    "XPeng": "XPEV",
    "Illumina Inc": "ILMN",
    "Illumina": "ILMN",
    "Exact Sciences Corp": "EXAS",
    "Exact Sciences": "EXAS",
    "Natera Inc": "NTRA",
    "Natera": "NTRA",
    "Pacific Biosciences": "PACB",
    "Pacbio": "PACB",
    "10x Genomics": "TXG",
    "Beam Therapeutics": "BEAM",
    "Editas Medicine": "EDIT",
    "Intellia Therapeutics": "NTLA",
    "Verve Therapeutics": "VERV",
    "Recursion Pharmaceuticals": "RXRX",
    "Schrödinger Inc": "SDGR",
    "Schrödinger": "SDGR",
    "Twist Bioscience": "TWST",
    "Guardant Health": "GH",
    "SomaLogic": "SLGC",
    "Quanterix": "QTRX",
    "Standard BioTools": "LAB",
    "10X Genomics": "TXG",
    "Celsius Holdings": "CELH",
    "Dexcom Inc": "DXCM",
    "Dexcom": "DXCM",
    "Insulet Corp": "PODD",
    "Insulet": "PODD",
    "Masimo Corp": "MASI",
    "Masimo": "MASI",
    "iRhythm Technologies": "IRTC",
    "Inari Medical": "NARI",
    "Penumbra Inc": "PEN",
    "Penumbra": "PEN",
    "Tandem Diabetes Care": "TNDM",
    "Progyny Inc": "PGNY",
    "Hims & Hers Health": "HIMS",
    "Hims & Hers": "HIMS",
    "LifeStance Health": "LFST",
    "Oak Street Health": "OSH",
    "Cano Health": "CANO",
    "Agilon Health": "AGL",
    "Crystal Lake Medical": "CLMT",
    "Alignment Healthcare": "ALHC",
    "Oscar Health": "OSCR",
    "Clover Health": "CLOV",
    "Bright Health": "BHG",
    "Multiplan Corp": "MPLN",
    "MultiPlan": "MPLN",
    "Evolent Health": "EVH",
    "Globe Life": "GL",
    "Unum Group": "UNM",
    "Lincoln National": "LNC",
    "Voya Financial": "VOYA",
    "Principal Financial": "PFG",
    "Ameriprise Financial": "AMP",
    "Charles Schwab": "SCHW",
    "The Charles Schwab": "SCHW",
    "Interactive Brokers": "IBKR",
    "Cboe Global Markets": "CBOE",
    "Nasdaq Inc": "NDAQ",
    "CME Group": "CME",
    "Intercontinental Exchange": "ICE",
    "S&P Global": "SPGI",
    "Msci Inc": "MSCI",
    "MSCI Inc": "MSCI",
    "Morningstar Inc": "MORN",
    "Factset Research Systems": "FDS",
    "FactSet": "FDS",
    "Verisk Analytics": "VRSK",
    "Dun & Bradstreet": "DNB",
    "Equifax Inc": "EFX",
    "Transunion": "TRU",
    "Experian Plc": "EXPGY",
    "Fidelity National Info Svcs": "FIS",
    "Fidelity National Information": "FIS",
    "Global Payments": "GPN",
    "Fiserv Inc": "FISV",
    "Fiserv": "FISV",
    "Jack Henry & Associates": "JKHY",
    "SS&C Technologies": "SSNC",
    "Envestnet": "ENV",
    "Invesco Ltd": "IVZ",
    "Invesco": "IVZ",
    "Franklin Resources": "BEN",
    "T. Rowe Price": "TROW",
    "T Rowe Price": "TROW",
    "Ameriprise": "AMP",
    "Lpl Financial": "LPL",
    "LPL Financial": "LPL",
    "Raymond James Financial": "RJF",
    "Stifel Financial": "SF",
    "Piper Sandler": "PIPR",
    "Houlihan Lokey": "HLI",
    "Moelis & Co": "MC",
    "Evercore Inc": "EVR",
    "Evercore": "EVR",
    "Lazard Ltd": "LAZ",
    "Lazard": "LAZ",
    "Greenhill & Co": "GHL",
    "Houlihan Lokey Inc": "HLI",
    "Perella Weinberg Partners": "PWP",
    "Oppenheimer Holdings": "OPY",
    "B. Riley Financial": "RILY",
    "Wedbush": "WEDB",
    "Maxim Group": "MXIP",
}


def normalize_name(name):
    """Match the Title-Case normalization done in fetch_13f.py."""
    if not name:
        return ""
    return name.strip().title()


def lookup_ticker(name):
    """Look up ticker by normalized name, with fallback attempts."""
    if not name:
        return None
    normalized = normalize_name(name)

    # Direct lookup
    if normalized in TICKER_MAP:
        return TICKER_MAP[normalized]

    # Try without common suffixes
    for suffix in [" Inc", " Corp", " Corporation", " Co", " Ltd", " Plc",
                   " Group", " Holdings", " Inc.", " Corp.", " Co.", ".",
                   ", Inc.", ", Corp.", ", Co."]:
        if normalized.endswith(suffix):
            stripped = normalized[:-len(suffix)]
            if stripped in TICKER_MAP:
                return TICKER_MAP[stripped]

    return None


def backfill():
    data_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "data", "fund-holdings.json"
    )

    with open(data_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    filled = 0
    total = 0

    for fund_id, fund in data.get("funds", {}).items():
        for h in fund.get("top_holdings", []):
            total += 1
            # Only fill if missing
            if not h.get("ticker"):
                ticker = lookup_ticker(h.get("name", ""))
                if ticker:
                    h["ticker"] = ticker
                    filled += 1

            # Ensure 13G items have form_type (fallback)
            if h.get("is_13g") and not h.get("form_type"):
                h["form_type"] = "13G/D"

    with open(data_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"Backfilled {filled}/{total} holdings with tickers.")
    print(f"Data written to {data_path}")


if __name__ == "__main__":
    backfill()
